# This is a basic workflow to help you get started with Actions

name: npm_publish

# 执行脚本的生命周期
on:
  workflow_dispatch:
  #选择在 push 到 github 时触发工作流
  push:
    #分支可以选择多个
    branches: [main]

# 一个 workflow 可以有多个 job
jobs:
  build:
    # 指定操作系统为'ubuntu-latest'
    runs-on: ubuntu-latest
    steps:
      # 检查仓库以便作业能正常访问
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      # 发布命令
      - run: npm publish
        env:
          # npm_token 就是刚刚填写 token 时取的名字
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    